#!/bin/bash
# generate_test_data.sh — Parse the ES2 MUD codebase to generate test data
# Extracts room exits and NPC locations from LPC source files.
#
# Output:
#   data/room_paths.txt  — room exit mappings
#   data/npc_rooms.txt   — NPC-to-room mappings

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
MUDLIB_DIR="$(cd "$SCRIPT_DIR/../mudlib" && pwd)"
DATA_DIR="$SCRIPT_DIR/data"

mkdir -p "$DATA_DIR"

ROOM_FILE="$DATA_DIR/room_paths.txt"
NPC_FILE="$DATA_DIR/npc_rooms.txt"

echo "Scanning mudlib at: $MUDLIB_DIR"
echo ""

# --------------------------------------------------------------------------
# Generate room_paths.txt
# Parse set("exits", ...) from room files
# --------------------------------------------------------------------------
echo "Generating room exit data..."

cat > "$ROOM_FILE" <<'EOF'
# Room exit data — auto-generated by generate_test_data.sh
# Format: start_room_path	direction	destination_path
# Paths are relative to mudlib root (e.g., /d/snow/inn_hall)
EOF

# Find all .c files under d/ that are likely room files (not in npc/ or obj/ subdirs)
find "$MUDLIB_DIR/d" -name "*.c" -type f | while read -r filepath; do
    # Skip npc and obj directories — those are NPCs and items, not rooms
    case "$filepath" in
        */npc/* | */obj/*) continue ;;
    esac

    # Get the MUD path (strip mudlib prefix, strip .c extension)
    mud_path="${filepath#$MUDLIB_DIR}"
    mud_path="${mud_path%.c}"

    # Get the directory of this file (for resolving __DIR__ relative paths)
    file_dir="$(dirname "$mud_path")"

    # Extract exits block — look for set("exits", ([...]))
    # This is a multi-line pattern, so we use perl for robust parsing
    perl -0777 -ne '
        my $file = "'"$mud_path"'";
        my $dir = "'"$file_dir"'";

        # Match set("exits", ([ ... ]))
        if (/set\s*\(\s*"exits"\s*,\s*\(\[\s*(.*?)\s*\]\)/s) {
            my $exits_block = $1;

            # Parse each "direction" : path pair
            while ($exits_block =~ /"(\w+)"\s*:\s*(?:__DIR__\s*"([^"]+)"|"([^"]+)")/g) {
                my $direction = $1;
                my $rel_path = $2;
                my $abs_path = $3;

                my $dest;
                if (defined $rel_path) {
                    # __DIR__ relative path
                    $dest = "$dir/$rel_path";
                } elsif (defined $abs_path) {
                    $dest = $abs_path;
                }

                if (defined $dest) {
                    # Clean up path (remove trailing whitespace)
                    $dest =~ s/\s+$//;
                    print "$file\t$direction\t$dest\n";
                }
            }
        }
    ' "$filepath"
done >> "$ROOM_FILE"

ROOM_COUNT=$(grep -c $'^\/' "$ROOM_FILE" 2>/dev/null || echo "0")
echo "  Found $ROOM_COUNT room exit entries"

# --------------------------------------------------------------------------
# Generate npc_rooms.txt
# Parse set("objects", ...) from room files
# --------------------------------------------------------------------------
echo "Generating NPC presence data..."

cat > "$NPC_FILE" <<'EOF'
# NPC room data — auto-generated by generate_test_data.sh
# Format: room_path	npc_id	npc_file_path
# npc_id is the basename of the NPC file
EOF

find "$MUDLIB_DIR/d" -name "*.c" -type f | while read -r filepath; do
    # Skip npc and obj directories
    case "$filepath" in
        */npc/* | */obj/*) continue ;;
    esac

    mud_path="${filepath#$MUDLIB_DIR}"
    mud_path="${mud_path%.c}"
    file_dir="$(dirname "$mud_path")"

    # Extract objects block — look for set("objects", ([...]))
    perl -0777 -ne '
        my $file = "'"$mud_path"'";
        my $dir = "'"$file_dir"'";

        if (/set\s*\(\s*"objects"\s*,\s*\(\[\s*(.*?)\s*\]\)/s) {
            my $objects_block = $1;

            # Parse each path : count pair
            while ($objects_block =~ /(?:__DIR__\s*"([^"]+)"|"([^"]+)")\s*:\s*(\d+)/g) {
                my $rel_path = $1;
                my $abs_path = $2;
                my $count = $3;

                my $obj_path;
                if (defined $rel_path) {
                    $obj_path = "$dir/$rel_path";
                } elsif (defined $abs_path) {
                    $obj_path = $abs_path;
                }

                if (defined $obj_path) {
                    # Only include NPC-like paths (contain /npc/)
                    if ($obj_path =~ /\/npc\//) {
                        my $npc_id = $obj_path;
                        $npc_id =~ s/.*\///;  # Get basename
                        $obj_path =~ s/\s+$//;
                        print "$file\t$npc_id\t$obj_path\n";
                    }
                }
            }
        }
    ' "$filepath"
done >> "$NPC_FILE"

NPC_COUNT=$(grep -c $'^\/' "$NPC_FILE" 2>/dev/null || echo "0")
echo "  Found $NPC_COUNT NPC-in-room entries"

echo ""
echo "Data files generated:"
echo "  $ROOM_FILE ($ROOM_COUNT entries)"
echo "  $NPC_FILE ($NPC_COUNT entries)"
echo ""
echo "Done."
